import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex justify-center mt-5'>
        <Link href="/" className='mr-3'>Main</Link>
        <Link href="/create">글작성</Link>
        </div>
        {children}</body>
    </html>
  )
}
